// Client-facing emails in the client's language (en / it / ar). Each template returns { subject, text }.
// Admin emails stay in English. `L(lang)` normalises anything unknown to English.
export const L = (lang) => (["en", "it", "ar"].includes(lang) ? lang : "en");
const first = (name) => (name || "").split(" ")[0] || "";
const J = (lines) => lines.filter((l) => l !== null && l !== undefined).join("\n");

const T = {
  magic_link: {
    en: (v) => ({ subject: v.created ? "Welcome to Zen Recovery — your sign-in link" : "Your Zen Recovery sign-in link", text: J([`Hi ${v.name},`, ``, `Tap to sign in (the link works for 20 minutes):`, v.link, ``, `If you didn't ask for this, ignore it.`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: v.created ? "Benvenuto in Zen Recovery — il tuo link di accesso" : "Il tuo link di accesso a Zen Recovery", text: J([`Ciao ${v.name},`, ``, `Tocca per accedere (il link vale 20 minuti):`, v.link, ``, `Se non l'hai richiesto tu, ignora questa email.`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: v.created ? "أهلاً بك في Zen Recovery — رابط تسجيل الدخول" : "رابط تسجيل الدخول إلى Zen Recovery", text: J([`مرحباً ${v.name}،`, ``, `اضغط لتسجيل الدخول (الرابط صالح لمدة 20 دقيقة):`, v.link, ``, `إذا لم تطلب هذا، تجاهل الرسالة.`, ``, `Zen Recovery`]) }),
  },
  welcome: {
    en: (v) => ({ subject: "Welcome to Zen Recovery", text: J([`Hi ${v.first || "there"},`, ``, `Your Zen Recovery account is ready. Cupping, manual therapy and recovery in Cairo, Dahab and Florence.`, ``, `What's in your account: ${v.site}/account`, `· two minutes of questions so we know which room is nearest and how to work with your body`, `· your sessions, before/after advice, and a progress check-in`, `· rewards: every few sessions one is free, and your friends get a discount through your invite link`, ``, `Book a session: ${v.site}/booking`, ``, `See you on the table,`, `Zen Recovery`]) }),
    it: (v) => ({ subject: "Benvenuto in Zen Recovery", text: J([`Ciao ${v.first || ""},`, ``, `Il tuo account Zen Recovery è pronto. Coppettazione, terapia manuale e recupero al Cairo, a Dahab e a Firenze.`, ``, `Cosa trovi nel tuo account: ${v.site}/account`, `· due minuti di domande per sapere quale sede è più vicina e come lavorare con il tuo corpo`, `· le tue sedute, i consigli prima/dopo e un check-in sui progressi`, `· premi: ogni poche sedute una è gratis, e i tuoi amici hanno uno sconto con il tuo link d'invito`, ``, `Prenota una seduta: ${v.site}/booking`, ``, `Ci vediamo sul lettino,`, `Zen Recovery`]) }),
    ar: (v) => ({ subject: "أهلاً بك في Zen Recovery", text: J([`مرحباً ${v.first || ""}،`, ``, `حسابك في Zen Recovery جاهز. حجامة وعلاج يدوي واستشفاء في القاهرة ودهب وفلورنسا.`, ``, `ماذا يوجد في حسابك: ${v.site}/account`, `· دقيقتان من الأسئلة لنعرف أقرب مكان لك وكيف نتعامل مع جسمك`, `· جلساتك، ونصائح قبل وبعد الجلسة، ومتابعة تقدمك`, `· المكافآت: كل عدة جلسات جلسة مجانية، وأصدقاؤك يحصلون على خصم عبر رابط الدعوة الخاص بك`, ``, `احجز جلسة: ${v.site}/booking`, ``, `نراك على السرير،`, `Zen Recovery`]) }),
  },
  booking_confirmed: {
    en: (v) => ({ subject: `Your Zen Recovery session in ${v.city} — ${v.date}`, text: J([`Hi ${v.name},`, ``, `Your session is reserved: ${v.service}, ${v.date}, ${v.slot}${v.therapist ? ` with ${v.therapist}` : ""}. ${v.paid}.`, ``, v.where ? `Where: ${v.where}` : null, v.where ? `` : null, v.exact ? `Zen will message you on WhatsApp (${v.phone}) ${v.where ? "before the session with anything to bring" : "with the address and anything to bring"}.` : `Zen will message you on WhatsApp (${v.phone}) to confirm the exact hour.`, ``, `Before: eat something light, drink water. After: keep warm, no cold showers or swimming for about six hours.`, ``, `Your sessions, rewards and invite link: ${v.site}/account`, ``, `See you soon,`, `Zen Recovery`]) }),
    it: (v) => ({ subject: `La tua seduta Zen Recovery a ${v.city} — ${v.date}`, text: J([`Ciao ${v.name},`, ``, `La tua seduta è prenotata: ${v.service}, ${v.date}, ${v.slot}${v.therapist ? ` con ${v.therapist}` : ""}. ${v.paid}.`, ``, v.where ? `Dove: ${v.where}` : null, v.where ? `` : null, v.exact ? `Zen ti scriverà su WhatsApp (${v.phone}) ${v.where ? "prima della seduta con cosa portare" : "con l'indirizzo e cosa portare"}.` : `Zen ti scriverà su WhatsApp (${v.phone}) per confermare l'ora esatta.`, ``, `Prima: mangia qualcosa di leggero e bevi acqua. Dopo: stai al caldo, niente docce fredde o nuoto per circa sei ore.`, ``, `Le tue sedute, i premi e il link d'invito: ${v.site}/account`, ``, `A presto,`, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `جلستك في Zen Recovery في ${v.city} — ${v.date}`, text: J([`مرحباً ${v.name}،`, ``, `تم حجز جلستك: ${v.service}، ${v.date}، ${v.slot}${v.therapist ? ` مع ${v.therapist}` : ""}. ${v.paid}.`, ``, v.where ? `المكان: ${v.where}` : null, v.where ? `` : null, v.exact ? `سيراسلك Zen على واتساب (${v.phone}) ${v.where ? "قبل الجلسة بما تحتاج إحضاره" : "بالعنوان وما تحتاج إحضاره"}.` : `سيراسلك Zen على واتساب (${v.phone}) لتأكيد الساعة بالضبط.`, ``, `قبل الجلسة: كُل شيئاً خفيفاً واشرب ماء. بعدها: حافظ على الدفء، ولا استحمام بارد ولا سباحة لنحو ست ساعات.`, ``, `جلساتك ومكافآتك ورابط الدعوة: ${v.site}/account`, ``, `نراك قريباً،`, `Zen Recovery`]) }),
  },
  booking_review: {
    en: (v) => ({ subject: `Zen Recovery — one quick check before ${v.date}`, text: J([`Hi ${v.name},`, ``, `Thanks for booking ${v.service} in ${v.city} on ${v.date} (${v.slot}).`, ``, `Because of what you told us about your health, a therapist looks at your answers first — that's normal and usually quick. Nothing has been charged. You'll get a confirmation (and a WhatsApp) once it's approved, and you pay at the session.`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `Zen Recovery — un controllo veloce prima del ${v.date}`, text: J([`Ciao ${v.name},`, ``, `Grazie per aver prenotato ${v.service} a ${v.city} il ${v.date} (${v.slot}).`, ``, `Per quello che ci hai detto sulla tua salute, un terapista guarda prima le tue risposte: è normale e di solito è veloce. Non è stato addebitato nulla. Riceverai una conferma (e un WhatsApp) appena approvata, e paghi alla seduta.`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `Zen Recovery — مراجعة سريعة قبل ${v.date}`, text: J([`مرحباً ${v.name}،`, ``, `شكراً لحجزك ${v.service} في ${v.city} يوم ${v.date} (${v.slot}).`, ``, `بسبب ما أخبرتنا به عن صحتك، سيطّلع معالج على إجاباتك أولاً — هذا طبيعي وعادة سريع. لم يتم خصم أي مبلغ. ستصلك رسالة تأكيد (وواتساب) بعد الموافقة، وتدفع في الجلسة.`, ``, `Zen Recovery`]) }),
  },
  cleared: {
    en: (v) => ({ subject: "Zen Recovery — you're cleared to book", text: J([`Hi ${v.first},`, ``, `A therapist looked at what you told us about your health and you're good to go.`, v.confirmed ? `Your pending session is now confirmed — Zen will message you on WhatsApp about the exact hour, and you pay at the session.` : `You can now book online like anyone else.`, ``, `${v.site}/account`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: "Zen Recovery — puoi prenotare", text: J([`Ciao ${v.first},`, ``, `Un terapista ha guardato quello che ci hai detto sulla tua salute e va tutto bene.`, v.confirmed ? `La tua seduta in attesa è ora confermata: Zen ti scriverà su WhatsApp per l'ora esatta, e paghi alla seduta.` : `Ora puoi prenotare online come tutti.`, ``, `${v.site}/account`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: "Zen Recovery — يمكنك الحجز الآن", text: J([`مرحباً ${v.first}،`, ``, `اطّلع معالج على ما أخبرتنا به عن صحتك وكل شيء على ما يرام.`, v.confirmed ? `جلستك المعلّقة مؤكدة الآن — سيراسلك Zen على واتساب بخصوص الساعة بالضبط، وتدفع في الجلسة.` : `يمكنك الآن الحجز عبر الموقع كأي شخص آخر.`, ``, `${v.site}/account`, ``, `Zen Recovery`]) }),
  },
  reminder: {
    en: (v) => ({ subject: `Tomorrow: your ${v.service} session in ${v.city}`, text: J([`Hi ${v.first},`, ``, `A reminder that your ${v.service} session in ${v.city} is tomorrow, ${v.date}, ${v.slot}.`, ``, `Before you come: eat something light 1–2 hours before, drink water, no alcohol or hard training today, clean skin with no lotion.`, ``, `Need to move it? Reply to Zen on WhatsApp as early as you can.`, ``, `Your account: ${v.site}/account`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `Domani: la tua seduta ${v.service} a ${v.city}`, text: J([`Ciao ${v.first},`, ``, `Un promemoria: la tua seduta ${v.service} a ${v.city} è domani, ${v.date}, ${v.slot}.`, ``, `Prima di venire: mangia qualcosa di leggero 1–2 ore prima, bevi acqua, niente alcol né allenamenti pesanti oggi, pelle pulita senza creme.`, ``, `Devi spostarla? Scrivi a Zen su WhatsApp il prima possibile.`, ``, `Il tuo account: ${v.site}/account`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `غداً: جلسة ${v.service} في ${v.city}`, text: J([`مرحباً ${v.first}،`, ``, `تذكير بأن جلسة ${v.service} في ${v.city} غداً، ${v.date}، ${v.slot}.`, ``, `قبل الحضور: كُل شيئاً خفيفاً قبلها بساعة أو ساعتين، اشرب ماء، لا كحول ولا تمرين شاق اليوم، وبشرة نظيفة بدون كريمات.`, ``, `تحتاج إلى تغيير الموعد؟ راسل Zen على واتساب في أقرب وقت.`, ``, `حسابك: ${v.site}/account`, ``, `Zen Recovery`]) }),
  },
  followup: {
    en: (v) => ({ subject: `How do you feel after your ${v.service} session?`, text: J([`Hi ${v.first},`, ``, `Two days on from your ${v.service} session. How's the body?`, ``, `Thirty seconds in your account tells your therapist what changed, and shows you your own progress over time:`, `${v.site}/account#progress`, ``, `And if the session was good, rating it there helps the room a lot.`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `Come ti senti dopo la seduta ${v.service}?`, text: J([`Ciao ${v.first},`, ``, `Sono passati due giorni dalla tua seduta ${v.service}. Come sta il corpo?`, ``, `Trenta secondi nel tuo account dicono al terapista cos'è cambiato e ti mostrano i tuoi progressi nel tempo:`, `${v.site}/account#progress`, ``, `E se la seduta è andata bene, una valutazione lì aiuta molto.`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `كيف تشعر بعد جلسة ${v.service}؟`, text: J([`مرحباً ${v.first}،`, ``, `مرّ يومان على جلسة ${v.service}. كيف حال جسمك؟`, ``, `ثلاثون ثانية في حسابك تخبر معالجك بما تغيّر، وتريك تقدمك مع الوقت:`, `${v.site}/account#progress`, ``, `وإذا كانت الجلسة جيدة، فتقييمها هناك يساعدنا كثيراً.`, ``, `Zen Recovery`]) }),
  },
  birthday: {
    en: (v) => ({ subject: `Happy birthday — ${v.pct}% off a session, until ${v.until}`, text: J([`Hi ${v.first},`, ``, `Your birthday is close. There's ${v.pct}% off one session in your account, any city, valid until ${v.until} (five days after your birthday). After that it's gone until next year.`, ``, `Book it: ${v.site}/booking`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `Buon compleanno — ${v.pct}% di sconto su una seduta, fino al ${v.until}`, text: J([`Ciao ${v.first},`, ``, `Il tuo compleanno è vicino. Nel tuo account c'è il ${v.pct}% di sconto su una seduta, in qualsiasi città, valido fino al ${v.until} (cinque giorni dopo il compleanno). Poi sparisce fino all'anno prossimo.`, ``, `Prenotala: ${v.site}/booking`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `عيد ميلاد سعيد — خصم ${v.pct}% على جلسة حتى ${v.until}`, text: J([`مرحباً ${v.first}،`, ``, `عيد ميلادك قريب. في حسابك خصم ${v.pct}% على جلسة واحدة، في أي مدينة، صالح حتى ${v.until} (خمسة أيام بعد عيد ميلادك). بعدها ينتهي حتى العام القادم.`, ``, `احجزها: ${v.site}/booking`, ``, `Zen Recovery`]) }),
  },
  waitlist: {
    en: (v) => ({ subject: `A slot opened in ${v.city} on ${v.date}`, text: J([`Hi ${v.first},`, ``, `Free times in ${v.city} on ${v.date}: ${v.times}.`, ``, `Book it before someone else does: ${v.link}`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `Si è liberato un posto a ${v.city} il ${v.date}`, text: J([`Ciao ${v.first},`, ``, `Orari liberi a ${v.city} il ${v.date}: ${v.times}.`, ``, `Prenota prima che lo prenda qualcun altro: ${v.link}`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `تحرّر موعد في ${v.city} يوم ${v.date}`, text: J([`مرحباً ${v.first}،`, ``, `الأوقات المتاحة في ${v.city} يوم ${v.date}: ${v.times}.`, ``, `احجزه قبل أن يسبقك أحد: ${v.link}`, ``, `Zen Recovery`]) }),
  },
  package_ready: {
    en: (v) => ({ subject: `Your ${v.pack} is ready — ${v.sessions} sessions in ${v.city}`, text: J([`Hi ${v.first},`, ``, `${v.sessions} sessions are waiting in your account, valid until ${v.until}. When you book, pick "Use my package" and there's nothing to pay.`, ``, `${v.link}`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `Il tuo ${v.pack} è pronto — ${v.sessions} sedute a ${v.city}`, text: J([`Ciao ${v.first},`, ``, `${v.sessions} sedute ti aspettano nel tuo account, valide fino al ${v.until}. Quando prenoti, scegli "Usa il mio pacchetto" e non c'è nulla da pagare.`, ``, `${v.link}`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `باقتك ${v.pack} جاهزة — ${v.sessions} جلسات في ${v.city}`, text: J([`مرحباً ${v.first}،`, ``, `${v.sessions} جلسات بانتظارك في حسابك، صالحة حتى ${v.until}. عند الحجز اختر "استخدم باقتي" ولا يوجد ما تدفعه.`, ``, `${v.link}`, ``, `Zen Recovery`]) }),
  },
  gift_buyer: {
    en: (v) => ({ subject: `Your gift for ${v.recipient} — code ${v.code}`, text: J([`Hi ${v.first},`, ``, `Thank you. The gift is paid: ${v.service} in ${v.city}.`, ``, `Code: ${v.code}`, `Booking link: ${v.link}`, ``, v.emailed ? `We've emailed ${v.recipient} too.` : `Forward the code or the link to ${v.recipient}.`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `Il tuo regalo per ${v.recipient} — codice ${v.code}`, text: J([`Ciao ${v.first},`, ``, `Grazie. Il regalo è pagato: ${v.service} a ${v.city}.`, ``, `Codice: ${v.code}`, `Link per prenotare: ${v.link}`, ``, v.emailed ? `Abbiamo scritto anche a ${v.recipient}.` : `Inoltra il codice o il link a ${v.recipient}.`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `هديتك لـ ${v.recipient} — الرمز ${v.code}`, text: J([`مرحباً ${v.first}،`, ``, `شكراً لك. تم دفع الهدية: ${v.service} في ${v.city}.`, ``, `الرمز: ${v.code}`, `رابط الحجز: ${v.link}`, ``, v.emailed ? `أرسلنا رسالة إلى ${v.recipient} أيضاً.` : `أرسل الرمز أو الرابط إلى ${v.recipient}.`, ``, `Zen Recovery`]) }),
  },
  gift_recipient: {
    en: (v) => ({ subject: `A gift from ${v.buyer}: a Zen Recovery session`, text: J([`${v.buyer} has given you a ${v.service} session with Zen Recovery in ${v.city}.`, ``, v.message ? `"${v.message}"` : null, v.message ? `` : null, `Your gift code: ${v.code}`, ``, `Book your session here (the code fills itself in): ${v.link}`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `Un regalo da ${v.buyer}: una seduta Zen Recovery`, text: J([`${v.buyer} ti ha regalato una seduta ${v.service} con Zen Recovery a ${v.city}.`, ``, v.message ? `"${v.message}"` : null, v.message ? `` : null, `Il tuo codice regalo: ${v.code}`, ``, `Prenota qui la tua seduta (il codice si inserisce da solo): ${v.link}`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `هدية من ${v.buyer}: جلسة في Zen Recovery`, text: J([`أهداك ${v.buyer} جلسة ${v.service} مع Zen Recovery في ${v.city}.`, ``, v.message ? `"${v.message}"` : null, v.message ? `` : null, `رمز هديتك: ${v.code}`, ``, `احجز جلستك هنا (الرمز يُملأ تلقائياً): ${v.link}`, ``, `Zen Recovery`]) }),
  },
  referral_reward: {
    en: (v) => ({ subject: `${v.who} booked with Zen — your ${v.pct}% is ready`, text: J([`Hi ${v.name},`, ``, `${v.who} just booked their first session with your invite. You've got ${v.pct}% off your next session.`, ``, `Use it when you book: ${v.site}/booking`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `${v.who} ha prenotato con Zen — il tuo ${v.pct}% è pronto`, text: J([`Ciao ${v.name},`, ``, `${v.who} ha appena prenotato la prima seduta con il tuo invito. Hai il ${v.pct}% di sconto sulla prossima seduta.`, ``, `Usalo quando prenoti: ${v.site}/booking`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `${v.who} حجز مع Zen — خصمك ${v.pct}% جاهز`, text: J([`مرحباً ${v.name}،`, ``, `${v.who} حجز للتو أول جلسة بدعوتك. لديك خصم ${v.pct}% على جلستك القادمة.`, ``, `استخدمه عند الحجز: ${v.site}/booking`, ``, `Zen Recovery`]) }),
  },
  application_received: {
    en: (v) => ({ subject: "Your application to join Zen Recovery", text: J([`Hi ${v.first},`, ``, `Thanks for applying to work with Zen Recovery in ${v.city}. The owner reads every application personally and answers within a few days.`, ``, `What happens next: if it's a yes, you get your sign-in for the team admin by email, your profile goes live on the site and on "Near you", and clients can book you directly.`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: "La tua candidatura per Zen Recovery", text: J([`Ciao ${v.first},`, ``, `Grazie per la candidatura a lavorare con Zen Recovery a ${v.city}. Il titolare legge ogni candidatura personalmente e risponde entro pochi giorni.`, ``, `Cosa succede dopo: se è un sì, ricevi via email l'accesso all'area team, il tuo profilo va online sul sito e su "Vicino a te", e i clienti possono prenotarti direttamente.`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: "طلبك للانضمام إلى Zen Recovery", text: J([`مرحباً ${v.first}،`, ``, `شكرًا لتقديمك للعمل مع Zen Recovery في ${v.city}. يقرأ المالك كل طلب بنفسه ويرد خلال أيام قليلة.`, ``, `الخطوة التالية: إذا كانت الإجابة نعم، تصلك بيانات الدخول إلى لوحة الفريق بالبريد، وينشر ملفك على الموقع وعلى "بالقرب منك"، ويمكن للعملاء حجزك مباشرة.`, ``, `Zen Recovery`]) }),
  },
  application_approved: {
    en: (v) => ({ subject: "Welcome to the Zen Recovery team", text: J([`Hi ${v.first},`, ``, `You're in. Your profile is live on ${v.site}/team and on ${v.site}/find, and clients in ${v.city} can book you directly.`, ``, `Your team admin: ${v.site}/admin`, `Sign in:   ${v.signin}`, `Password:  ${v.password}`, ``, `Change the password under Settings after your first sign-in. In the admin you set your opening hours, days off, your own prices and your exact position ("Use my current position" in your profile).`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: "Benvenuto nel team Zen Recovery", text: J([`Ciao ${v.first},`, ``, `Sei dei nostri. Il tuo profilo è online su ${v.site}/team e su ${v.site}/find, e i clienti a ${v.city} possono prenotarti direttamente.`, ``, `Area team: ${v.site}/admin`, `Accesso:   ${v.signin}`, `Password:  ${v.password}`, ``, `Cambia la password in Impostazioni dopo il primo accesso. Nell'area team imposti orari, giorni liberi, i tuoi prezzi e la tua posizione esatta ("Usa la mia posizione" nel profilo).`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: "أهلاً بك في فريق Zen Recovery", text: J([`مرحباً ${v.first}،`, ``, `تم قبولك. ملفك الآن على ${v.site}/team وعلى ${v.site}/find، ويمكن للعملاء في ${v.city} حجزك مباشرة.`, ``, `لوحة الفريق: ${v.site}/admin`, `اسم الدخول: ${v.signin}`, `كلمة المرور: ${v.password}`, ``, `غيّر كلمة المرور من الإعدادات بعد أول دخول. من اللوحة تحدد ساعات عملك وأيام إجازتك وأسعارك وموقعك الدقيق ("استخدم موقعي الحالي" في ملفك).`, ``, `Zen Recovery`]) }),
  },
  chat_client: {   // 2026-09-13: a therapist wrote in the site chat; the client gets one email per half hour at most
    en: (v) => ({ subject: `${v.from} wrote to you on Zen Recovery`, text: J([`Hi ${v.first},`, ``, `${v.from} answered in your Zen Recovery chat:`, ``, `"${v.excerpt}"`, ``, `Read and reply here: ${v.link}`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `${v.from} ti ha scritto su Zen Recovery`, text: J([`Ciao ${v.first},`, ``, `${v.from} ha risposto nella tua chat Zen Recovery:`, ``, `"${v.excerpt}"`, ``, `Leggi e rispondi qui: ${v.link}`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `${v.from} راسلك على Zen Recovery`, text: J([`مرحباً ${v.first}،`, ``, `${v.from} ردّ في محادثتك على Zen Recovery:`, ``, `"${v.excerpt}"`, ``, `اقرأ وردّ من هنا: ${v.link}`, ``, `Zen Recovery`]) }),
  },
  application_declined: {
    en: (v) => ({ subject: "About your application to Zen Recovery", text: J([`Hi ${v.first},`, ``, `Thank you for applying. We're not adding therapists in ${v.city} right now${v.note ? `: ${v.note}` : "."}`, ``, `We keep your details for six months and get in touch if that changes.`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: "La tua candidatura a Zen Recovery", text: J([`Ciao ${v.first},`, ``, `Grazie per la candidatura. In questo momento non stiamo aggiungendo terapisti a ${v.city}${v.note ? `: ${v.note}` : "."}`, ``, `Conserviamo i tuoi dati per sei mesi e ti contattiamo se cambia qualcosa.`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: "بخصوص طلبك للانضمام إلى Zen Recovery", text: J([`مرحباً ${v.first}،`, ``, `شكرًا لتقديمك. لا نضيف معالجين في ${v.city} حاليًا${v.note ? `: ${v.note}` : "."}`, ``, `نحتفظ ببياناتك ستة أشهر ونتواصل معك إذا تغيّر الوضع.`, ``, `Zen Recovery`]) }),
  },
  booking_cancelled: {
    en: (v) => ({ subject: `Your Zen Recovery session on ${v.date} is cancelled`, text: J([`Hi ${v.name},`, ``, `Your ${v.service} on ${v.date} in ${v.city} is cancelled${v.by === "admin" ? " by Zen Recovery" : ""}.`, v.fee ? `Cancelled inside the ${v.hours}-hour window: ${v.fee} is kept, as in the booking rules.` : `No fee: it was outside the ${v.hours}-hour window.`, v.refund ? `Refund: ${v.refund}${v.refund_status === "done" ? ", back on your card within 5–10 days." : ", Zen will arrange it with you."}` : null, ``, `Book again whenever you like: ${v.site}/booking`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: `La tua seduta Zen Recovery del ${v.date} è annullata`, text: J([`Ciao ${v.name},`, ``, `La tua seduta ${v.service} del ${v.date} a ${v.city} è annullata${v.by === "admin" ? " da Zen Recovery" : ""}.`, v.fee ? `Annullata entro le ${v.hours} ore: viene trattenuto ${v.fee}, come da regole di prenotazione.` : `Nessun costo: era fuori dalla finestra di ${v.hours} ore.`, v.refund ? `Rimborso: ${v.refund}${v.refund_status === "done" ? ", sulla tua carta entro 5–10 giorni." : ", Zen lo concorderà con te."}` : null, ``, `Prenota di nuovo quando vuoi: ${v.site}/booking`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: `تم إلغاء جلستك في Zen Recovery بتاريخ ${v.date}`, text: J([`مرحباً ${v.name}،`, ``, `تم إلغاء جلسة ${v.service} بتاريخ ${v.date} في ${v.city}${v.by === "admin" ? " من قِبل Zen Recovery" : ""}.`, v.fee ? `الإلغاء خلال ${v.hours} ساعة من الموعد: يُحتفظ بمبلغ ${v.fee} وفق قواعد الحجز.` : `بدون رسوم: كان الإلغاء قبل ${v.hours} ساعة من الموعد.`, v.refund ? `الاسترداد: ${v.refund}${v.refund_status === "done" ? "، يعود إلى بطاقتك خلال 5–10 أيام." : "، وسيرتّب Zen ذلك معك."}` : null, ``, `احجز مجددًا متى شئت: ${v.site}/booking`, ``, `Zen Recovery`]) }),
  },
  loyalty_reward: {
    en: (v) => ({ subject: "Your next Zen session is on us", text: J([`Hi ${v.name},`, ``, `That was session number ${v.n}. The next one is free — pick a day whenever you like: ${v.site}/booking`, ``, `Zen Recovery`]) }),
    it: (v) => ({ subject: "La prossima seduta Zen la offriamo noi", text: J([`Ciao ${v.name},`, ``, `Quella era la seduta numero ${v.n}. La prossima è gratis: scegli un giorno quando vuoi: ${v.site}/booking`, ``, `Zen Recovery`]) }),
    ar: (v) => ({ subject: "جلستك القادمة في Zen على حسابنا", text: J([`مرحباً ${v.name}،`, ``, `كانت تلك الجلسة رقم ${v.n}. القادمة مجانية — اختر اليوم الذي يناسبك: ${v.site}/booking`, ``, `Zen Recovery`]) }),
  },
};
// Paid line for the confirmation, by language.
export function paidLineFor(lang, bk, fmt) {
  const l = L(lang), free = { en: "Free session (reward)", it: "Seduta gratuita (premio)", ar: "جلسة مجانية (مكافأة)" }, pack = { en: "Package session (no charge)", it: "Seduta del pacchetto (nessun addebito)", ar: "جلسة من الباقة (بدون دفع)" }, gift = { en: "Gift voucher (no charge)", it: "Buono regalo (nessun addebito)", ar: "قسيمة هدية (بدون دفع)" };
  if (bk.amount === 0) return bk.discount_kind === "package" ? pack[l] : bk.discount_kind === "gift" ? gift[l] : free[l];
  const applied = { en: "applied, list", it: "applicato, listino", ar: "مطبّق، السعر الأصلي" }[l];
  return `${fmt(bk.amount, bk.currency)}${bk.discount_kind ? ` (${bk.discount_kind} ${applied} ${fmt(bk.list_amount, bk.currency)})` : ""}`;
}
export const M = (key, lang, vars) => (T[key][L(lang)] || T[key].en)(vars);
export const firstName = first;
